spring.application.name=consultant-recruiter-management

spring.datasource.url=jdbc:mysql://localhost:3306/consultant_recruiter_management
spring.datasource.username=crmuser
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6d4308e9a5b270
spring.mail.password=01bf7b891a6e08
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true